# Nome da aplicação
spring.application.name=delivery-performance-tracker

# Configuração do Banco de Dados H2 em memória
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o Console Visual do H2 no navegador para você ver as tabelas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Estratégia de criação de tabelas (update atualiza a estrutura sem apagar os dados enquanto o app roda)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG